[package]
name = "public-key-101-spruceid"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
did-key = "0.2"
form_urlencoded = "1.2.2"
serde_json = "1.0"
textnonce = "1.0"
dashmap = "6.1"
urlencoding = "2.1"
